image: python:3.11
install: |
  pip install -r requirements.txt
  pip install -r requirements-dev.txt
test: |
  pytest --cov=myapp
  flake8
build: |
  python setup.py bdist_wheel
env: |
  DATABASE_URL=sqlite:///test.db
  DEBUG=false
